"""Idempotence check (Determinism Stack #7).

A faithful code-author run on its own output should produce the same output
— the converter applied to its own input is a no-op. If wave-N+1 ≠ wave-N
for byte-identical input, the persona is non-deterministic in ways that
temp=0 + seed pinning cannot mask.

The check has two parts:

1. **Orchestration** (`build_self_input` / `run_idempotence_check`): given a
   run_id, build the "second-pass" prompt that asks code-author to convert
   its own Java back to Java. Calls Codex via the same Coordinator the F5
   pipeline uses. This part is impure — it shells out to Codex.

2. **Comparison** (`compare_java_trees`): pure dict-of-files diff between
   first-pass output and second-pass output, AST-equivalent via
   `core.determinism.diff_ast_java`.

The orchestration layer is thin — the deterministic part is `compare_java_trees`,
and that's what the validator actually consumes.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from app.core.determinism import diff_ast_java, diff_byte


@dataclass
class FileDiff:
    path: str
    ast_equal: bool
    byte_equal: bool


@dataclass
class IdempotenceResult:
    ok: bool                                  # True iff every file is AST-equivalent
    files_total: int
    files_byte_equal: int
    files_ast_equal: int
    file_diffs: list[FileDiff] = field(default_factory=list)
    missing_in_second_pass: list[str] = field(default_factory=list)
    extra_in_second_pass: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "ok": self.ok,
            "files_total": self.files_total,
            "files_byte_equal": self.files_byte_equal,
            "files_ast_equal": self.files_ast_equal,
            "missing_in_second_pass": self.missing_in_second_pass,
            "extra_in_second_pass": self.extra_in_second_pass,
            "file_diffs": [
                {"path": d.path, "ast_equal": d.ast_equal, "byte_equal": d.byte_equal}
                for d in self.file_diffs
            ],
        }


def compare_java_trees(first_root: Path, second_root: Path) -> IdempotenceResult:
    """Compare two Java output trees file-by-file. Pure function."""
    first_files = {str(p.relative_to(first_root)): p for p in first_root.rglob("*.java")}
    second_files = {str(p.relative_to(second_root)): p for p in second_root.rglob("*.java")}

    common = sorted(set(first_files) & set(second_files))
    missing = sorted(set(first_files) - set(second_files))
    extra = sorted(set(second_files) - set(first_files))

    file_diffs: list[FileDiff] = []
    byte_equal_count = 0
    ast_equal_count = 0

    for path in common:
        a = first_files[path].read_text(errors="replace")
        b = second_files[path].read_text(errors="replace")
        byte_eq = diff_byte(a, b)
        ast_eq = diff_ast_java(a, b)
        file_diffs.append(FileDiff(path=path, ast_equal=ast_eq, byte_equal=byte_eq))
        if byte_eq:
            byte_equal_count += 1
        if ast_eq:
            ast_equal_count += 1

    ok = not missing and not extra and ast_equal_count == len(common)
    return IdempotenceResult(
        ok=ok,
        files_total=len(common),
        files_byte_equal=byte_equal_count,
        files_ast_equal=ast_equal_count,
        file_diffs=file_diffs,
        missing_in_second_pass=missing,
        extra_in_second_pass=extra,
    )


def build_self_input_context(first_pass_java_files: dict[str, str]) -> str:
    """Build a Context Pack-style input that hands the first-pass Java back to code-author.

    The persona is asked: "given THIS Java module (which was generated from a COBOL source),
    produce the Java module again." Expected: no-op. Caller invokes Codex with code-author.md
    + this context.
    """
    sections: list[str] = []
    sections.append("# Self-input Context Pack (idempotence test)\n")
    sections.append(
        "This is a second-pass invocation. The Java module below was generated by you in a previous run "
        "from the same COBOL source. Re-emit the Java module. Expected: byte-identical or AST-equivalent output.\n"
    )
    sections.append("---\n## Java module (first-pass output)\n")
    for path, body in sorted(first_pass_java_files.items()):
        sections.append(f"### `{path}`\n```java\n{body}\n```\n\n")
    return "".join(sections)
